// Map of toolId → dedicated page component
// Every tool has a dedicated page
import { lazy } from 'react'

export const TOOL_COMPONENTS = {
  // Foundations
  'gen-ai':          lazy(() => import('./foundations/GenAIPage')),
  'prompt-eng':      lazy(() => import('./foundations/PromptEngPage')),
  'loop-engineering':lazy(() => import('./foundations/LoopEngineeringPage')),
  'rag':             lazy(() => import('./foundations/RAGPage')),
  'embeddings':      lazy(() => import('./foundations/EmbeddingsPage')),
  'fine-tuning':     lazy(() => import('./foundations/FineTuningPage')),
  'model-training':  lazy(() => import('./foundations/ModelTrainingPage')),
  'benchmark-evals': lazy(() => import('./foundations/BenchmarkEvalsPage')),
  // Chatbots
  'ms-copilot':      lazy(() => import('./chatbots/MsCopilotPage')),
  'chatgpt':         lazy(() => import('./chatbots/ChatGPTPage')),
  'claude':          lazy(() => import('./chatbots/ClaudePage')),
  'gemini':          lazy(() => import('./chatbots/GeminiPage')),
  'perplexity':      lazy(() => import('./chatbots/PerplexityPage')),
  'notebooklm':      lazy(() => import('./chatbots/NotebookLMPage')),
  'youcom':          lazy(() => import('./chatbots/YouComPage')),
  'huggingchat':     lazy(() => import('./chatbots/HuggingChatPage')),
  'deepseek':        lazy(() => import('./chatbots/DeepSeekPage')),
  'grok':            lazy(() => import('./chatbots/GrokPage')),
  'qwen':            lazy(() => import('./chatbots/QwenPage')),
  'kimi':            lazy(() => import('./chatbots/KimiPage')),
  // Builders
  'bolt-new':        lazy(() => import('./builders/BoltNewPage')),
  'v0':              lazy(() => import('./builders/V0Page')),
  'replit':          lazy(() => import('./builders/ReplitPage')),
  'lovable':         lazy(() => import('./builders/LovablePage')),
  'streamlit':       lazy(() => import('./builders/StreamlitPage')),
  'gradio':          lazy(() => import('./builders/GradioPage')),
  'vercel-ai-sdk':   lazy(() => import('./builders/VercelAISDKPage')),
  // Coding
  'claude-code':     lazy(() => import('./coding/ClaudeCodePage')),
  'copilot':         lazy(() => import('./coding/CopilotPage')),
  'cursor':          lazy(() => import('./coding/CursorPage')),
  'windsurf':        lazy(() => import('./coding/WindsurfPage')),
  'gemini-cli':      lazy(() => import('./coding/GeminiCLIPage')),
  'codeium':         lazy(() => import('./coding/CodeiumPage')),
  'amazon-q':        lazy(() => import('./coding/AmazonQPage')),
  'cline':           lazy(() => import('./coding/ClinePage')),
  'aider':           lazy(() => import('./coding/AiderPage')),
  'continue-dev':    lazy(() => import('./coding/ContinueDevPage')),
  'tabnine':         lazy(() => import('./coding/TabninePage')),
  'openai-codex':    lazy(() => import('./coding/OpenAICodexPage')),
  'jules':           lazy(() => import('./coding/JulesPage')),
  'trae':            lazy(() => import('./coding/TraePage')),
  'qodo':            lazy(() => import('./coding/QodoPage')),
  // APIs
  'gemini-api':      lazy(() => import('./apis/GeminiAPIPage')),
  'groq':            lazy(() => import('./apis/GroqPage')),
  'openai-api':      lazy(() => import('./apis/OpenAIAPIPage')),
  'together-ai':     lazy(() => import('./apis/TogetherAIPage')),
  'huggingface':     lazy(() => import('./apis/HuggingFacePage')),
  'openrouter':      lazy(() => import('./apis/OpenRouterPage')),
  'anthropic-api':   lazy(() => import('./apis/AnthropicAPIPage')),
  'aws-bedrock':     lazy(() => import('./apis/AWSBedrockPage')),
  'azure-openai':    lazy(() => import('./apis/AzureOpenAIPage')),
  'mistral-api':     lazy(() => import('./apis/MistralAPIPage')),
  'replicate':       lazy(() => import('./apis/ReplicatePage')),
  'google-ai-studio': lazy(() => import('./apis/GoogleAIStudioPage')),
  'cerebras':        lazy(() => import('./apis/CerebrasPage')),
  'sambanova':       lazy(() => import('./apis/SambaNovaPage')),
  'cohere':          lazy(() => import('./apis/CoherePage')),
  // Agents
  'langchain':       lazy(() => import('./agents/LangChainPage')),
  'langgraph':       lazy(() => import('./agents/LangGraphPage')),
  'crewai':          lazy(() => import('./agents/CrewAIPage')),
  'autogen':         lazy(() => import('./agents/AutoGenPage')),
  'metagpt':         lazy(() => import('./agents/MetaGPTPage')),
  'openclaw':        lazy(() => import('./agents/OpenClawPage')),
  'hermes':          lazy(() => import('./agents/HermesPage')),
  'mcp':             lazy(() => import('./agents/MCPPage')),
  'llamaindex':      lazy(() => import('./agents/LlamaIndexPage')),
  'pydantic-ai':     lazy(() => import('./agents/PydanticAIPage')),
  'smolagents':      lazy(() => import('./agents/SmolagentsPage')),
  // Automation
  'n8n':             lazy(() => import('./automation/N8NPage')),
  'flowise':         lazy(() => import('./automation/FlowisePage')),
  'dify':            lazy(() => import('./automation/DifyPage')),
  'zapier':          lazy(() => import('./automation/ZapierPage')),
  'ifttt':           lazy(() => import('./automation/IFTTTPage')),
  'make':            lazy(() => import('./automation/MakePage')),
  // Local AI
  'ollama':          lazy(() => import('./local/OllamaPage')),
  'lmstudio':        lazy(() => import('./local/LMStudioPage')),
  'oobabooga':       lazy(() => import('./local/OobaboogaPage')),
  'litelllm':        lazy(() => import('./local/LiteLLMPage')),
  'localai':         lazy(() => import('./local/LocalAIPage')),
  'jan':             lazy(() => import('./local/JanPage')),
  // Vector
  'chromadb':        lazy(() => import('./vector/ChromaDBPage')),
  'pinecone':        lazy(() => import('./vector/PineconePage')),
  'qdrant':          lazy(() => import('./vector/QdrantPage')),
  'weaviate':        lazy(() => import('./vector/WeaviatePage')),
  'supabase-vector': lazy(() => import('./vector/SupabasePage')),
  // Data
  'julius':          lazy(() => import('./data/JuliusPage')),
  'code-interpreter':lazy(() => import('./data/CodeInterpreterPage')),
  'langfuse':        lazy(() => import('./data/LangfusePage')),
  'modal':           lazy(() => import('./data/ModalPage')),
  'colab':           lazy(() => import('./data/ColabPage')),
  'kaggle':          lazy(() => import('./data/KagglePage')),
  'wandb':           lazy(() => import('./data/WandbPage')),
  // Creative
  'dalle-free':      lazy(() => import('./creative/BingImagePage')),
  'stable-diffusion':lazy(() => import('./creative/StableDiffusionPage')),
  'midjourney':      lazy(() => import('./creative/MidjourneyPage')),
  'flux':            lazy(() => import('./creative/FLUXPage')),
  'gamma':           lazy(() => import('./creative/GammaPage')),
  'canva-ai':        lazy(() => import('./creative/CanvaAIPage')),
  'ideogram':        lazy(() => import('./creative/IdeogramPage')),
  'leonardo':        lazy(() => import('./creative/LeonardoPage')),
  // Voice
  'whisper':         lazy(() => import('./voice/WhisperPage')),
  'elevenlabs':      lazy(() => import('./voice/ElevenLabsPage')),
  // Career
  'teal':            lazy(() => import('./career/TealPage')),
  'notion-ai':       lazy(() => import('./career/NotionAIPage')),
  'grammarly':       lazy(() => import('./career/GrammarlyPage')),
  'pramp':           lazy(() => import('./career/PrampPage')),
  'rezi':            lazy(() => import('./career/ReziPage')),
  'kickresume':      lazy(() => import('./career/KickresumePage')),
  // Security
  'snyk':            lazy(() => import('./security/SnykPage')),
  'sonarqube':       lazy(() => import('./security/SonarQubePage')),
  'github-adv-sec':  lazy(() => import('./security/GitHubAdvSecPage')),
  'gitguardian':     lazy(() => import('./security/GitGuardianPage')),
  'wiz':             lazy(() => import('./security/WizPage')),
  'semgrep':         lazy(() => import('./security/SemgrepPage')),
  'trivy':           lazy(() => import('./security/TrivyPage')),
  // Video & Music
  'runway':          lazy(() => import('./media/RunwayPage')),
  'kling':           lazy(() => import('./media/KlingPage')),
  'luma':            lazy(() => import('./media/LumaPage')),
  'pika':            lazy(() => import('./media/PikaPage')),
  'suno':            lazy(() => import('./media/SunoPage')),
  'udio':            lazy(() => import('./media/UdioPage')),
}
