// ─── Stack cards  (ordered: frontend → fullstack → backend → AI & ML → databases)
export const STACKS = [
  // ── Frontend ──────────────────────────────────────────────────────────────
  {
    id: 'html-static',
    route: '/deployment/html-static',
    emoji: '🌐',
    title: 'HTML / CSS / JS Site',
    subtitle: 'Static website',
    desc: 'Deploy a pure HTML, CSS, and JavaScript website to GitHub Pages. Free forever, no build step, live in minutes directly from your GitHub repo.',
    color: '#F59E0B',
    platforms: 'GitHub Pages',
    stackType: 'frontend',
    tags: ['html', 'css', 'javascript', 'static', 'github pages', 'portfolio', 'website', 'no framework', 'beginner', 'landing page'],
  },
  {
    id: 'react',
    route: '/deployment/react',
    emoji: '⚛️',
    title: 'React App',
    subtitle: 'Frontend only',
    desc: 'Deploy a React / Vite project to Vercel. Free forever with HTTPS and custom domain.',
    color: '#60A5FA',
    platforms: 'Vercel',
    stackType: 'frontend',
    tags: ['react', 'vite', 'javascript', 'frontend', 'vercel', 'spa', 'portfolio', 'web app', 'static'],
  },
  {
    id: 'vue',
    route: '/deployment/vue',
    emoji: '💚',
    title: 'Vue.js App',
    subtitle: 'Frontend only (Vite)',
    desc: 'Deploy a Vue 3 / Vite app to Vercel, Netlify, or Cloudflare Pages — free forever, HTTPS, custom domain. Includes the SPA fallback fix so Vue Router works on refresh.',
    color: '#42B883',
    platforms: 'Vercel / Netlify',
    stackType: 'frontend',
    tags: ['vue', 'vuejs', 'vue 3', 'vite', 'javascript', 'frontend', 'vercel', 'netlify', 'cloudflare pages', 'spa', 'portfolio', 'vue router'],
  },
  // ── JavaScript Full Stack ─────────────────────────────────────────────────
  {
    id: 'nextjs',
    route: '/deployment/nextjs',
    emoji: '▲',
    title: 'Next.js',
    subtitle: 'Full-stack React framework',
    desc: 'Deploy a Next.js app to Vercel — made by the same team, one-click deploy, SSR and API routes all work free. No build configuration needed.',
    color: '#E2E8F0',
    platforms: 'Vercel',
    stackType: 'fullstack',
    tags: ['nextjs', 'next', 'react', 'javascript', 'ssr', 'vercel', 'full stack', 'api routes', 'frontend'],
  },
  {
    id: 'mern',
    route: '/deployment/mern',
    emoji: '🔷',
    title: 'MERN Stack',
    subtitle: 'MongoDB + Express + React + Node',
    desc: 'Deploy a full MERN stack — React frontend on Vercel, Express/Node backend on Render, MongoDB Atlas as database. Three free services, all connected.',
    color: '#61DAFB',
    platforms: 'Vercel + Render + Atlas',
    stackType: 'fullstack',
    tags: ['mern', 'react', 'nodejs', 'express', 'mongodb', 'full stack', 'javascript', 'vercel', 'render'],
  },
  // ── JavaScript Backend ────────────────────────────────────────────────────
  {
    id: 'nodejs',
    route: '/deployment/nodejs',
    emoji: '🟢',
    title: 'Node.js / Express',
    subtitle: 'Express REST API',
    desc: 'Deploy a Node.js + Express REST API to Render. No Docker needed — Render detects Node.js automatically from package.json. Includes MongoDB Atlas and PostgreSQL options.',
    color: '#68A063',
    platforms: 'Render',
    stackType: 'backend',
    tags: ['nodejs', 'node', 'express', 'javascript', 'backend', 'api', 'rest', 'render', 'mongodb', 'mongoose'],
  },
  // ── Python Backend ────────────────────────────────────────────────────────
  {
    id: 'django-backend',
    route: '/deployment/django',
    emoji: '🎸',
    title: 'Django Backend',
    subtitle: 'Django REST API + PostgreSQL',
    desc: 'Deploy your Django REST API on Render with Render PostgreSQL (built-in). Neon PostgreSQL also shown as a free alternative.',
    color: '#4ADE80',
    platforms: 'Render + PostgreSQL',
    stackType: 'backend',
    tags: ['django', 'python', 'backend', 'api', 'rest api', 'postgresql', 'database', 'render', 'neon', 'full stack'],
  },
  {
    id: 'django-fullstack',
    route: '/deployment/django-fullstack',
    emoji: '🐍',
    title: 'Django Full Stack',
    subtitle: 'Django templates + PostgreSQL',
    desc: 'Deploy a complete Django web app — templates, static files, and PostgreSQL — all on Render. No separate frontend framework needed.',
    color: '#34D399',
    platforms: 'Render + PostgreSQL',
    stackType: 'fullstack',
    tags: ['django', 'python', 'full stack', 'templates', 'postgresql', 'render', 'web app', 'backend', 'frontend', 'jinja', 'html'],
  },
  {
    id: 'fastapi',
    route: '/deployment/fastapi',
    emoji: '⚡',
    title: 'FastAPI',
    subtitle: 'Python REST API (ASGI)',
    desc: 'Deploy a FastAPI application to Render. No Docker needed — Render detects Python from requirements.txt. Great for AI/ML projects and modern Python APIs.',
    color: '#009688',
    platforms: 'Render',
    stackType: 'backend',
    tags: ['fastapi', 'python', 'backend', 'api', 'rest', 'asgi', 'uvicorn', 'render', 'ai', 'ml', 'mongodb'],
  },
  {
    id: 'flask',
    route: '/deployment/flask',
    emoji: '🌶',
    title: 'Flask',
    subtitle: 'Python Web Framework',
    desc: 'Deploy a Flask application to Render. Lightweight Python web framework — no Docker needed, gunicorn as the production server, PostgreSQL or MongoDB Atlas.',
    color: '#F97316',
    platforms: 'Render',
    stackType: 'backend',
    tags: ['flask', 'python', 'backend', 'api', 'wsgi', 'gunicorn', 'render', 'mongodb', 'postgresql', 'web'],
  },
  // ── Java Backend ──────────────────────────────────────────────────────────
  {
    id: 'springboot',
    route: '/deployment/springboot',
    emoji: '🍃',
    title: 'Spring Boot',
    subtitle: 'Spring Boot + Docker + PostgreSQL / MongoDB',
    desc: 'Deploy any Spring Boot application to Render using Docker — REST API, MVC templates, or full stack. Render has no native Java runtime so Docker is required. Includes PostgreSQL and MongoDB Atlas options.',
    color: '#6DB33F',
    platforms: 'Render + Docker',
    stackType: 'backend',
    tags: ['spring boot', 'java', 'backend', 'api', 'rest api', 'mvc', 'thymeleaf', 'docker', 'postgresql', 'mongodb', 'render', 'jwt', 'spring', 'maven', 'jpa', 'full stack'],
  },
  // ── AI & ML ──────────────────────────────────────────────────────────────
  {
    id: 'streamlit',
    route: '/deployment/streamlit',
    emoji: '📊',
    title: 'Streamlit — ML Model Deployment',
    subtitle: 'Any ML/DL model that fits in 1GB RAM',
    desc: 'Deploy any ML or DL model as a live web app — sklearn, XGBoost, PyTorch, TensorFlow/Keras, Pandas dashboards. The only limit is 1GB RAM. Large transformer models (BERT, GPT) need HF Spaces instead.',
    color: '#FF4B4B',
    platforms: 'Streamlit Cloud',
    stackType: 'mldata',
    tags: ['streamlit', 'python', 'machine learning', 'data science', 'ml', 'dashboard', 'sklearn', 'pandas', 'plotly', 'model deployment'],
  },
  {
    id: 'heavy-model-deploy',
    route: '/deployment/heavy-model-deploy',
    emoji: '🧠',
    title: 'Large / Heavy Model Deploy',
    subtitle: 'Models > 1GB RAM — PyTorch, TF, DL models',
    desc: 'Deploy large ML/DL models that exceed Streamlit Cloud\'s 1GB RAM limit. Store model weights on HF Model Hub, load at runtime on HF Spaces (16GB RAM free). Works for any framework.',
    color: '#8B5CF6',
    platforms: 'HF Spaces + Model Hub',
    stackType: 'mldata',
    tags: ['large model', 'heavy model', 'pytorch', 'tensorflow', 'keras', 'deep learning', 'hugging face', 'model hub', 'gradio', 'gpu', 'deployment'],
  },
  {
    id: 'chatbot-deploy',
    route: '/deployment/chatbot-deploy',
    emoji: '💬',
    title: 'Chatbot / AI Chat Demo',
    subtitle: 'Deploy your chatbot as a live demo',
    desc: 'Turn your chatbot project into a live web demo — OpenAI, HuggingFace, or any LLM. Uses Gradio ChatInterface. Free to deploy, shareable link, no web framework needed.',
    color: '#9B6ED4',
    platforms: 'HF Spaces',
    stackType: 'mldata',
    tags: ['chatbot', 'llm', 'openai', 'chat', 'conversational ai', 'gradio', 'demo', 'ai', 'hugging face'],
  },
  {
    id: 'nlp-demo',
    route: '/deployment/nlp-demo',
    emoji: '📝',
    title: 'NLP / Text AI Demo',
    subtitle: 'Sentiment · Classification · Summarization',
    desc: 'Deploy NLP demos — sentiment analysis, text classification, summarization, NER using HuggingFace transformers. Gradio interface, free 16GB RAM, live in minutes.',
    color: '#60A5FA',
    platforms: 'HF Spaces',
    stackType: 'mldata',
    tags: ['nlp', 'text', 'sentiment', 'classification', 'transformers', 'bert', 'gradio', 'ai', 'hugging face'],
  },
  {
    id: 'image-ai',
    route: '/deployment/image-ai',
    emoji: '🖼️',
    title: 'Image AI Demo',
    subtitle: 'Classification · Detection · Vision models',
    desc: 'Deploy image classification or object detection demos — upload an image, get AI predictions. Uses vision transformers or YOLO via Gradio. Free 16GB RAM.',
    color: '#4ADE80',
    platforms: 'HF Spaces',
    stackType: 'mldata',
    tags: ['computer vision', 'image', 'classification', 'detection', 'vit', 'yolo', 'gradio', 'ai', 'cv', 'hugging face'],
  },
  {
    id: 'rag-app',
    route: '/deployment/rag-app',
    emoji: '📄',
    title: 'RAG / Document Q&A App',
    subtitle: 'Upload PDF → ask questions → get AI answers',
    desc: 'Deploy a Retrieval-Augmented Generation app — upload any PDF and ask questions. Uses LangChain + FAISS + embeddings. Free 16GB RAM handles most RAG setups.',
    color: '#F59E0B',
    platforms: 'HF Spaces',
    stackType: 'mldata',
    tags: ['rag', 'langchain', 'pdf', 'document qa', 'faiss', 'embeddings', 'gradio', 'ai', 'llm', 'hugging face'],
  },
  // ── Bots, Apps & Automation ───────────────────────────────────────────────
  {
    id: 'discord-bot',
    route: '/deployment/discord-bot',
    emoji: '🤖',
    title: 'Discord Bot',
    subtitle: 'Slash-command bot, truly free & 24/7',
    desc: 'Host a Discord bot free and always-online with Cloudflare Workers (slash commands). Includes the honest truth about gateway bots and where discord.py / discord.js can actually run free.',
    color: '#5865F2',
    platforms: 'Cloudflare Workers',
    stackType: 'apps',
    tags: ['discord', 'bot', 'discord.py', 'discord.js', 'cloudflare workers', 'slash commands', 'interactions', 'gateway', 'python', 'javascript', 'always on', '24/7'],
  },
  {
    id: 'scraper-automation',
    route: '/deployment/scraper-automation',
    emoji: '⏰',
    title: 'Web Scraper / Automation',
    subtitle: 'Scheduled scripts on a timer',
    desc: 'Run a web scraper, data pipeline, or scheduled script for free with GitHub Actions (cron). No server — results commit back to your repo automatically. Honest about UTC timing and limits.',
    color: '#FBBF24',
    platforms: 'GitHub Actions',
    stackType: 'apps',
    tags: ['scraper', 'web scraping', 'automation', 'cron', 'scheduled', 'github actions', 'python', 'beautifulsoup', 'data pipeline', 'monitor', 'workflow'],
  },
  {
    id: 'expo-mobile',
    route: '/deployment/expo-mobile',
    emoji: '📱',
    title: 'React Native / Expo',
    subtitle: 'Ship a real mobile app — free',
    desc: 'Share a React Native (Expo) app for free — Expo Go QR, a downloadable Android APK, and a hosted web build. Honest about which parts are free vs. the paid app stores.',
    color: '#4630EB',
    platforms: 'Expo EAS',
    stackType: 'apps',
    tags: ['react native', 'expo', 'eas', 'mobile', 'android', 'ios', 'apk', 'app', 'expo go', 'eas build', 'eas update', 'javascript'],
  },
  // ── Databases ─────────────────────────────────────────────────────────────
  {
    id: 'mongodb-atlas',
    route: '/deployment/mongodb-atlas',
    emoji: '🍃',
    title: 'MongoDB Atlas',
    subtitle: 'Free NoSQL database — forever',
    desc: 'Set up a free MongoDB Atlas cluster (M0, 512MB, never expires). Connect it to Node.js, Python (PyMongo/Motor), Django, FastAPI, Flask, and Spring Boot with exact connection string formats.',
    color: '#00ED64',
    platforms: 'MongoDB Atlas',
    stackType: 'database',
    tags: ['mongodb', 'nosql', 'database', 'atlas', 'mongoose', 'motor', 'pymongo', 'free forever', 'node', 'python', 'spring boot'],
  },
  {
    id: 'neon-postgres',
    route: '/deployment/neon-postgres',
    emoji: '⚡',
    title: 'Neon PostgreSQL',
    subtitle: 'Free SQL database — 0.5GB/project, data safe',
    desc: 'Set up a free Neon PostgreSQL database (0.5GB/project, data preserved). Connect it to Node.js (pg/Prisma), Python (psycopg2/SQLAlchemy), Django, FastAPI, Flask, and Spring Boot.',
    color: '#A78BFA',
    platforms: 'Neon',
    stackType: 'database',
    tags: ['postgresql', 'sql', 'neon', 'database', 'prisma', 'sqlalchemy', 'psycopg2', 'free forever', 'node', 'python', 'spring boot', 'django'],
  },
  {
    id: 'supabase',
    route: '/deployment/supabase',
    emoji: '🟢',
    title: 'Supabase',
    subtitle: 'PostgreSQL + Auth + Storage — free',
    desc: 'Set up a free Supabase project (PostgreSQL, 500MB, forever free). Use Supabase as a database, get built-in auth, and connect to Node.js, Python, and React.',
    color: '#3ECF8E',
    platforms: 'Supabase',
    stackType: 'database',
    tags: ['supabase', 'postgresql', 'sql', 'database', 'auth', 'free forever', 'node', 'python', 'react', 'nextjs'],
  },
  {
    id: 'render-postgres',
    route: '/deployment/render-postgres',
    emoji: '🐘',
    title: 'Render PostgreSQL',
    subtitle: 'Free SQL database — 1GB, 30 days',
    desc: 'Set up a free Render PostgreSQL database (1GB). Easy to link directly to Render backend services. Free tier expires after 30 days — best for demos and short-term projects.',
    color: '#4ADE80',
    platforms: 'Render',
    stackType: 'database',
    tags: ['postgresql', 'sql', 'render', 'database', 'free', '30 days', 'node', 'python', 'django', 'spring boot'],
  },
]

// ─── Free platforms ──────────────────────────────────────────────────────────
export const PLATFORMS = [
  {
    name: 'Vercel', emoji: '▲',
    desc: 'Deploy React, Next.js, or any frontend app instantly from GitHub',
    free: 'Free forever',
    color: '#60A5FA', url: 'vercel.com',
    stackType: 'frontend',
    tags: ['vercel', 'frontend', 'react', 'nextjs', 'static', 'javascript', 'spa', 'portfolio'],
  },
  {
    name: 'Netlify', emoji: '◆',
    desc: 'Deploy frontend apps via drag & drop or GitHub — good alternative to Vercel',
    free: 'Free forever',
    color: '#00C7B7', url: 'netlify.com',
    stackType: 'frontend',
    tags: ['netlify', 'frontend', 'react', 'html', 'static', 'javascript', 'deploy'],
  },
  {
    name: 'Render', emoji: '🖥',
    desc: 'Host Django, Node.js, or Spring Boot backends — free PostgreSQL included (expires in 30 days, use Neon for long-term)',
    free: 'Free (sleeps on idle, DB 30 days)',
    color: '#4ADE80', url: 'render.com',
    stackType: 'backend',
    tags: ['render', 'backend', 'django', 'python', 'nodejs', 'postgresql', 'docker', 'spring boot'],
  },
  {
    name: 'GitHub', emoji: '🐙',
    desc: 'Host your code — required by Vercel, Netlify, and Render for auto-deploy',
    free: 'Always free',
    color: '#F59E0B', url: 'github.com',
    stackType: 'all',
    tags: ['github', 'git', 'code', 'version control', 'source', 'repo', 'frontend', 'backend'],
  },
  {
    name: 'GitHub Pages', emoji: '📄',
    desc: 'Free hosting for HTML/CSS/JS sites directly from your GitHub repository',
    free: 'Free forever',
    color: '#F97316', url: 'pages.github.com',
    stackType: 'frontend',
    tags: ['github pages', 'html', 'css', 'javascript', 'static', 'portfolio', 'frontend'],
  },
  {
    name: 'Cloudflare Pages', emoji: '⚡',
    desc: 'Deploy static sites & SPAs from GitHub on Cloudflare\'s global edge — free SSL, custom domain, unlimited bandwidth',
    free: 'Free forever, unlimited bandwidth',
    color: '#F6821F', url: 'pages.cloudflare.com',
    stackType: 'frontend',
    tags: ['cloudflare', 'pages', 'frontend', 'static', 'react', 'spa', 'edge', 'cdn', 'html'],
  },
  {
    name: 'Firebase Hosting', emoji: '🔥',
    desc: 'Static & SPA hosting on Google\'s CDN with custom domain and free SSL — no credit card needed',
    free: 'Free — 10 GB storage, 10 GB/mo transfer',
    color: '#FFCA28', url: 'firebase.google.com/docs/hosting',
    stackType: 'frontend',
    tags: ['firebase', 'google', 'frontend', 'static', 'spa', 'react', 'cdn', 'hosting', 'ssl'],
  },
  {
    name: 'MongoDB Atlas', emoji: '🍃',
    desc: 'Free NoSQL cloud database — M0 cluster, 512MB, truly free forever, 1 free cluster per project',
    free: '512MB, free forever',
    color: '#00ED64', url: 'cloud.mongodb.com',
    stackType: 'backend',
    tags: ['mongodb', 'database', 'nosql', 'atlas', 'spring boot', 'django', 'nodejs', 'backend'],
  },
  {
    name: 'Neon', emoji: '⚡',
    desc: 'Serverless PostgreSQL — 0.5GB per project, data preserved forever, compute auto-suspends after 5 min idle',
    free: '0.5GB/project, data safe forever',
    color: '#A78BFA', url: 'neon.tech',
    stackType: 'backend',
    tags: ['neon', 'database', 'postgresql', 'postgres', 'sql', 'serverless', 'backend'],
  },
  {
    name: 'Supabase', emoji: '🟢',
    desc: 'PostgreSQL + Auth + Storage — 500MB free, pauses after 7 days DB inactivity (data safe, resume in 1 min)',
    free: '500MB, pauses if idle 7 days',
    color: '#3ECF8E', url: 'supabase.com',
    stackType: 'backend',
    tags: ['supabase', 'postgresql', 'database', 'auth', 'storage', 'backend', 'full stack'],
  },
  {
    name: 'Cloudinary', emoji: '☁️',
    desc: 'Image & video CDN storage — solves the Render ephemeral filesystem problem for media uploads',
    free: '25 GB free, no expiry',
    color: '#3448C5', url: 'cloudinary.com',
    stackType: 'backend',
    tags: ['cloudinary', 'images', 'media', 'storage', 'cdn', 'django', 'spring boot', 'files'],
  },
  {
    name: 'Railway', emoji: '🚂',
    desc: 'Deploy Docker apps with databases easily — sleek alternative to Render',
    free: '$5 credit/month',
    color: '#9B6ED4', url: 'railway.app',
    stackType: 'backend',
    tags: ['railway', 'docker', 'backend', 'deploy', 'nodejs', 'spring boot', 'django'],
  },
  {
    name: 'Koyeb', emoji: '🚀',
    desc: 'Host one backend web service free (512MB RAM) — sleeps after 1 hr idle, a solid Render alternative',
    free: 'Free web service (sleeps on idle)',
    color: '#7C3AED', url: 'koyeb.com',
    stackType: 'backend',
    tags: ['koyeb', 'backend', 'deploy', 'nodejs', 'python', 'fastapi', 'flask', 'docker'],
  },
  {
    name: 'Upstash', emoji: '🟩',
    desc: 'Serverless Redis for caching & sessions — scales to zero, costs nothing when idle',
    free: 'Free — 256 MB, 500K commands/mo',
    color: '#00E9A3', url: 'upstash.com',
    stackType: 'backend',
    tags: ['upstash', 'redis', 'cache', 'caching', 'serverless', 'sessions', 'backend', 'database'],
  },
  {
    name: 'cron-job.org', emoji: '⏰',
    desc: 'Free cron jobs to ping your Render backend every 10 min and prevent sleep',
    free: 'Unlimited free jobs',
    color: '#F59E0B', url: 'cron-job.org',
    stackType: 'all',
    tags: ['cron', 'ping', 'keepalive', 'render', 'sleep', 'uptime', 'backend'],
  },
  {
    name: 'GitHub Actions', emoji: '⚙️',
    desc: 'Run scrapers, scheduled scripts & automation on a cron timer — no server needed',
    free: 'Public repos: unlimited · Private: 2,000 min/mo',
    color: '#4ADE80', url: 'github.com/features/actions',
    stackType: 'apps',
    tags: ['github actions', 'cron', 'scraper', 'automation', 'scheduled', 'ci', 'workflow', 'python'],
  },
  {
    name: 'Cloudflare Workers', emoji: '⚡',
    desc: 'Serverless functions that never sleep — ideal for a free, always-on Discord slash-command bot',
    free: 'Free — 100,000 requests/day',
    color: '#F6821F', url: 'workers.cloudflare.com',
    stackType: 'apps',
    tags: ['cloudflare workers', 'serverless', 'discord', 'bot', 'always on', 'edge', 'functions'],
  },
  {
    name: 'Expo EAS', emoji: '📱',
    desc: 'Cloud build & update service for React Native apps — free Android APK builds and OTA updates',
    free: 'Free — 15 Android + 15 iOS builds/mo',
    color: '#4630EB', url: 'expo.dev',
    stackType: 'apps',
    tags: ['expo', 'eas', 'react native', 'mobile', 'android', 'apk', 'build', 'ios'],
  },
  {
    name: 'Streamlit Cloud', emoji: '📊',
    desc: 'Deploy Python data apps and ML models — no web framework, just app.py + requirements.txt',
    free: '3 apps free, 1GB RAM each',
    color: '#FF4B4B', url: 'streamlit.io/cloud',
    stackType: 'mldata',
    tags: ['streamlit', 'python', 'machine learning', 'data science', 'dashboard', 'ml', 'free'],
  },
  {
    name: 'Hugging Face Spaces', emoji: '🤗',
    desc: 'ML demo platform — 16GB RAM free, Streamlit/Gradio, ideal for NLP and AI model demos',
    free: 'CPU free forever (2vCPU, 16GB RAM)',
    color: '#FF9D00', url: 'huggingface.co/spaces',
    stackType: 'mldata',
    tags: ['hugging face', 'machine learning', 'gradio', 'nlp', 'transformers', 'ai', 'ml', 'free'],
  },
]

// ─── React guide  (order: 01 02 03 06 05 08 04 09 07 11 13) ──────────────────
