export const HTML_STATIC_GUIDE = [
  {
    phase: '01',
    title: 'What is GitHub Pages and why use it?',
    color: '#F59E0B',
    steps: [
      {
        label: 'GitHub Pages — free hosting directly from your repo',
        isText: true,
        text: [
          'GitHub Pages is a free hosting service built into every GitHub repository.',
          'You push your HTML/CSS/JS files to GitHub and they go live instantly.',
          'No build step. No server setup. No credit card needed.',
          '',
          'What you get free:',
          '✅ Live URL: username.github.io/repo-name',
          '✅ Automatic HTTPS — SSL certificate included',
          '✅ Auto-deploy — every push to main updates your live site',
          '✅ Custom domain support — connect your own .com',
          '✅ Works for any static site — HTML, CSS, JS, Bootstrap, Tailwind',
          '',
          'Perfect for:',
          '→ Personal portfolio websites',
          '→ College project landing pages',
          '→ Resume websites',
          '→ Any project that does not need a backend server',
          '',
          'Limitation:',
          '→ Only static files — no Python, PHP, Node.js, or database',
          '→ If your site needs a backend, see the Django guides instead',
        ],
        note: 'GitHub Pages is the fastest way to get a live URL for a student portfolio. Push code → live in 2 minutes.',
      },
    ],
  },

  {
    phase: '02',
    title: 'Before deployment — checklist',
    color: '#9B6ED4',
    steps: [
      {
        label: 'Verify your site works before pushing',
        isText: true,
        text: [
          '✅ Open index.html directly in your browser (File → Open)',
          '   Every page should display correctly with no broken layouts',
          '',
          '✅ Your project has an index.html file at the root level',
          '   GitHub Pages serves index.html as the homepage by default',
          '',
          '✅ All links between pages are relative (not absolute):',
          '   Right: href="about.html" or href="./about.html"',
          '   Wrong: href="/Users/yourname/Desktop/project/about.html"',
          '',
          '✅ All image paths are relative:',
          '   Right: src="images/photo.jpg" or src="./images/photo.jpg"',
          '   Wrong: src="C:/Users/yourname/project/images/photo.jpg"',
          '',
          '✅ CSS and JS files are linked with relative paths:',
          '   Right: href="style.css" or href="./css/style.css"',
          '   Wrong: href="/home/user/project/style.css"',
          '',
          '✅ No broken images or 404 links when browsing locally',
          '✅ Site looks correct on mobile (open DevTools → device toolbar)',
        ],
        note: 'Absolute local file paths are the #1 cause of broken GitHub Pages sites. All paths must be relative — they work both locally and on GitHub Pages.',
      },
    ],
  },

  {
    phase: '03',
    title: 'Project structure for GitHub Pages',
    color: '#60A5FA',
    steps: [
      {
        label: 'Required file structure',
        isText: true,
        text: [
          'GitHub Pages requires index.html at the root of your repository.',
          '',
          'Recommended structure:',
          '',
          '   my-portfolio/          ← your repo root',
          '     index.html           ← homepage (REQUIRED at root)',
          '     about.html',
          '     projects.html',
          '     css/',
          '       style.css',
          '     js/',
          '       main.js',
          '     images/',
          '       photo.jpg',
          '       logo.png',
          '     fonts/               (if using local fonts)',
          '',
          'Link files from index.html like this:',
          '   <link rel="stylesheet" href="css/style.css">',
          '   <script src="js/main.js"></script>',
          '   <img src="images/photo.jpg" alt="My photo">',
          '',
          'No index.html = GitHub Pages shows a 404 or folder listing.',
          'Make sure index.html exists and is spelled correctly (all lowercase).',
        ],
        note: 'File and folder names on GitHub Pages are case-sensitive (Linux). "Images/Photo.jpg" and "images/photo.jpg" are different. Use lowercase everywhere to be safe.',
      },
    ],
  },

  {
    phase: '04',
    title: 'Create .gitignore',
    color: '#F59E0B',
    steps: [
      {
        label: 'Create .gitignore in your project root',
        isFile: true,
        fileName: '.gitignore',
        commands: [
          `# OS files — auto-generated, not needed in repo
.DS_Store
Thumbs.db
desktop.ini

# Editor files
.vscode/settings.json
.idea/
*.swp
*.swo

# Logs
*.log

# Temp files
*.tmp
~$*`,
        ],
        note: 'HTML/CSS/JS projects have very little to exclude. The main things are OS files (.DS_Store on Mac, Thumbs.db on Windows) and editor files.',
      },
    ],
  },

  {
    phase: '05',
    title: 'Push your site to GitHub',
    color: '#9B6ED4',
    steps: [
      {
        label: 'Create GitHub repo and push your code',
        isText: true,
        text: [
          '1. Go to github.com → click "+" → "New repository"',
          '2. Name: my-portfolio (or your project name)',
          '3. Set to Public (required for free GitHub Pages)',
          '4. Do NOT check "Add README" or "Add .gitignore"',
          '   Your project already has these',
          '5. Click "Create repository"',
        ],
        note: 'The repo must be Public for free GitHub Pages. Private repos need a paid GitHub account for Pages.',
      },
      {
        label: 'Initialize git and push',
        commands: [
          `git init`,
          `git add .`,
          `git commit -m "initial commit — portfolio site"`,
          `git branch -M main`,
          `git remote add origin https://github.com/YOUR_USERNAME/YOUR_REPO_NAME.git`,
          `git push -u origin main`,
        ],
        note: 'Replace YOUR_USERNAME and YOUR_REPO_NAME with your actual GitHub username and repo name.',
      },
    ],
  },

  {
    phase: '06',
    title: 'Enable GitHub Pages',
    color: '#4ADE80',
    steps: [
      {
        label: 'Turn on GitHub Pages in repo settings',
        isText: true,
        text: [
          '1. Open your GitHub repository',
          '2. Click "Settings" tab (top of the repo page)',
          '3. Scroll down to "Pages" in the left sidebar',
          '4. Under "Source" → select "Deploy from a branch"',
          '5. Branch: main',
          '   Folder: / (root)',
          '6. Click "Save"',
          '',
          'GitHub shows a banner:',
          '   "Your site is live at https://YOUR_USERNAME.github.io/YOUR_REPO/"',
          '',
          'Wait 1–2 minutes for the first deployment.',
          'Then open the URL — your site is live.',
          '',
          'Every future git push automatically updates the live site.',
          'Changes usually go live within 1 minute.',
        ],
        note: 'If the site does not load after 2 minutes, check the "Actions" tab in your repo — it shows the deployment status and any errors.',
      },
      {
        label: 'Special case: username.github.io repo',
        isText: true,
        text: [
          'If you name your repo exactly: YOUR_USERNAME.github.io',
          '(e.g. manmadha.github.io)',
          '',
          '→ GitHub automatically serves it at: https://YOUR_USERNAME.github.io/',
          '→ No need to enable Pages — it is on by default for this repo name',
          '→ This is your "root" GitHub Pages URL — perfect for a main portfolio',
          '',
          'For all other repos, the URL is:',
          '   https://YOUR_USERNAME.github.io/REPO_NAME/',
        ],
        note: 'Naming your repo YOUR_USERNAME.github.io gives you the cleanest URL (no /repo-name). This is the standard approach for a personal portfolio.',
      },
    ],
  },

  {
    phase: '07',
    title: 'Fix common path issues',
    color: '#EF4444',
    steps: [
      {
        label: 'Why paths break on GitHub Pages but work locally',
        isText: true,
        text: [
          'When you open a file locally, the browser uses file:// protocol.',
          'Paths like "./images/photo.jpg" work because the browser resolves them',
          'relative to your file location.',
          '',
          'On GitHub Pages, your site is served from:',
          '   https://username.github.io/repo-name/',
          '',
          'Root-relative paths starting with / cause problems:',
          '   src="/images/photo.jpg"',
          '   → browser looks for: https://username.github.io/images/photo.jpg',
          '   → NOT: https://username.github.io/repo-name/images/photo.jpg',
          '   → Image is missing',
          '',
          'Fix: use relative paths (no leading slash):',
          '   src="images/photo.jpg"     ✅',
          '   src="./images/photo.jpg"   ✅',
          '   src="/images/photo.jpg"    ❌',
          '',
          'Same rule for CSS and JS files:',
          '   href="css/style.css"       ✅',
          '   href="/css/style.css"      ❌',
        ],
        note: 'After pushing changes, wait 1 minute for GitHub Pages to redeploy, then hard-refresh with Ctrl+Shift+R to clear browser cache.',
      },
    ],
  },

  {
    phase: '08',
    title: 'Common errors and fixes',
    color: '#F97316',
    steps: [
      {
        label: '404 — page not found after enabling Pages',
        isText: true,
        text: [
          'Problem: GitHub Pages URL shows 404.',
          '',
          'Cause 1: No index.html at the root of the repository.',
          'Fix: Make sure index.html exists at the top level of your repo.',
          '   (Not inside a subfolder like src/index.html)',
          '',
          'Cause 2: Deployment not finished yet.',
          'Fix: Wait 1–2 minutes. Check the "Actions" tab in your repo.',
          '   A green checkmark means it is live.',
          '',
          'Cause 3: Pages not enabled correctly.',
          'Fix: Settings → Pages → verify Branch=main, Folder=/(root) → Save.',
        ],
        note: 'The Actions tab (next to Settings) shows deployment logs. A yellow spinner means deploying. Green tick means live. Red X means failed.',
      },
      {
        label: 'CSS not loading — unstyled page',
        isText: true,
        text: [
          'Problem: Site appears with no styling after deploy.',
          '',
          'Cause: CSS file path uses /css/style.css (root-relative) or absolute path.',
          '',
          'Fix: Change all CSS links to relative:',
          '   Wrong: <link href="/css/style.css" rel="stylesheet">',
          '   Right: <link href="css/style.css" rel="stylesheet">',
          '   Right: <link href="./css/style.css" rel="stylesheet">',
          '',
          'For Bootstrap CDN — always works (no path issue):',
          '   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">',
        ],
        note: 'CDN links (https://...) always work on GitHub Pages. Only local file paths need to be relative.',
      },
      {
        label: 'Images broken after deploy',
        isText: true,
        text: [
          'Problem: Images appear as broken icons on the live site.',
          '',
          'Cause 1: Absolute or root-relative paths.',
          'Fix: Use relative paths: src="images/photo.jpg"',
          '',
          'Cause 2: Wrong file name case (uppercase vs lowercase).',
          'Fix: GitHub Pages runs on Linux — case-sensitive.',
          '   If file is "Photo.jpg" and src is "photo.jpg" → broken.',
          '   Rename files to lowercase: photo.jpg, logo.png',
          '',
          'Cause 3: File not committed to GitHub.',
          'Fix: Run git status and check if the image file is tracked.',
          '   git add images/ && git commit -m "add images" && git push',
        ],
        note: 'Always use lowercase filenames for all assets. This avoids case sensitivity issues on GitHub Pages (Linux) vs your local machine (Windows/Mac).',
      },
    ],
  },

  {
    phase: '09',
    title: 'Custom domain (optional)',
    color: '#A78BFA',
    steps: [
      {
        label: 'Connect your own domain to GitHub Pages',
        isText: true,
        text: [
          'If you own a domain (e.g. yourname.com), you can connect it free.',
          '',
          '1. In your DNS provider, add a CNAME record:',
          '   Name:  www  (or @ for root)',
          '   Value: YOUR_USERNAME.github.io',
          '',
          '2. In GitHub → repo Settings → Pages → Custom domain:',
          '   Enter: www.yourname.com',
          '   Click Save',
          '',
          '3. Create a CNAME file in your repo root:',
          '   Content: www.yourname.com',
          '   (GitHub Pages creates this automatically when you save above)',
          '',
          '4. Check "Enforce HTTPS" after the SSL certificate generates',
          '   (can take 24 hours)',
          '',
          'Free domain options for students:',
          '→ .tech domains: get.tech (free 1 year with student verification)',
          '→ .me domains: Namecheap student offer',
          '→ GitHub Student Developer Pack: free .me domain + other perks',
          '   (Freenom .tk/.ml domains are no longer reliable — avoid them.)',
        ],
        note: 'Custom domain is optional — username.github.io/repo looks professional enough for a student portfolio. Add a domain only if you specifically want one.',
      },
    ],
  },

  {
    phase: '10',
    title: 'Free tier — GitHub Pages limits',
    color: '#34D399',
    steps: [
      {
        label: 'What the free tier includes and what the limits mean',
        isText: true,
        text: [
          'GitHub Pages free tier is very generous — for a student portfolio you',
          'will almost never hit its limits (they exist, but they are soft and high).',
          '',
          '✅ Bandwidth: 100 GB/month',
          '   A portfolio with 1,000 visitors/month uses ~1-5 GB.',
          '   You would need tens of thousands of visits to approach this.',
          '',
          '✅ Storage: 1 GB per repository',
          '   A typical portfolio with images is 5-50 MB.',
          '   Do not commit large video files — use YouTube embeds instead.',
          '',
          '✅ Build time: 10 minutes per build',
          '   Static HTML/CSS/JS has no build step — deploys instantly.',
          '',
          '✅ No server-side code allowed',
          '   GitHub Pages is for static files only.',
          '   For forms, contact emails, or databases — use a backend.',
          '',
          'When GitHub Pages is NOT enough:',
          '→ You need a database or user authentication',
          '→ You need server-side code (Python, Node.js)',
          '→ You need form submissions without a third-party service',
          '→ For these: use the Django or React + Django guides',
          '',
          'For student portfolios and HTML/CSS/JS projects:',
          'GitHub Pages is more than enough. Deploy and share your link.',
        ],
        note: 'GitHub Pages has been free and reliable since 2008. For static sites, it is the simplest and most dependable free hosting available.',
      },
    ],
  },
]

// ─── Django Full Stack → Render + PostgreSQL ─────────────────────────────────
