export const KOYEB_GUIDE = [
  {
    phase: '01',
    title: 'What is Koyeb and why use it?',
    color: '#7C3AED',
    steps: [
      {
        label: 'Koyeb — deploy apps & containers, a Render alternative',
        isText: true,
        text: [
          'Koyeb is a platform-as-a-service that runs your backend for you. Point',
          'it at a GitHub repo or a Docker image and it builds, deploys, and',
          'serves your app on their bare-metal infrastructure with HTTPS and a',
          'free *.koyeb.app URL.',
          '',
          'Two ways to deploy (both covered here):',
          '→ From GitHub — Koyeb auto-detects your stack (Node, Python, Go, etc.)',
          '  using buildpacks, or reads your Dockerfile if you have one',
          '→ From a Docker image — deploy any pre-built image from a registry',
          '',
          'Why students consider it (vs Render):',
          '→ Another genuinely free always-available slot for a backend',
          '→ Deploys from Docker OR source, so it fits almost any language',
          '→ Regions include Frankfurt, Washington D.C., and Singapore',
          '  (Singapore is the closest to India)',
          '',
          'Good for: a Node/Express, FastAPI, Flask, or Dockerized backend you',
          'want hosted free. Pair it with an external DB (Neon, Turso, Atlas).',
        ],
        note: 'Koyeb is best understood as "a Render-style host with a Docker-friendly free instance". Its big advantage for Indian students is a Singapore region option; its big limitation is a single free service that sleeps when idle (details next).',
      },
      {
        label: 'The free tier — VERIFIED 2026, and it has CHANGED',
        isText: true,
        text: [
          'Be careful: Koyeb\'s free tier is different from a couple of years ago.',
          '',
          'What is FREE today (per organization):',
          '→ ONE free web Service',
          '     512 MB RAM, 0.1 vCPU, 2 GB SSD',
          '     region: Frankfurt, Washington D.C., or Singapore',
          '     scales to ZERO after ~1 hour with no traffic (then cold-starts',
          '     on the next request)',
          '→ ONE free PostgreSQL database',
          '     1 GB storage, and only 5 HOURS of active compute per month',
          '',
          'What CHANGED (the honest part):',
          '→ The old "$5.50/month free credit" from the 2022–2023 preview is',
          '  GONE (removed Feb 1, 2024). It was replaced by the fixed "free"',
          '  instance above — so you get one small always-eligible service, not',
          '  a credit you can spend however you like.',
          '→ The free instance canNOT be a Worker, canNOT use custom scaling,',
          '  and canNOT attach a persistent Volume.',
          '',
          'The free Postgres 5-hours/month caveat:',
          '→ 5 hours of ACTIVE compute is very little — it suits light dev/demo',
          '  use, not a constantly-queried production DB. For anything real,',
          '  use Neon/Turso/Atlas free tiers instead and just host the app here.',
        ],
        note: 'The most important honest point: Koyeb no longer gives a spendable free credit — it gives ONE small free web service (that sleeps after ~1h idle) and ONE very limited free Postgres (5 active hours/month). Treat the free Postgres as a toy; put real data in Neon/Turso/Atlas.',
      },
    ],
  },

  {
    phase: '02',
    title: 'Deploy from GitHub (buildpack or Dockerfile)',
    color: '#7C3AED',
    steps: [
      {
        label: 'Prepare your app: read the PORT env var',
        isFile: true,
        fileName: 'server.js (Node example)',
        commands: [
          `// Koyeb injects a PORT env var — bind to it and to 0.0.0.0
const port = process.env.PORT || 8000;
app.listen(port, '0.0.0.0', () => {
  console.log(\`listening on \${port}\`);
});`,
        ],
        note: 'Like most PaaS hosts, Koyeb tells your app which port to use via the PORT env var and expects it bound to 0.0.0.0. Hard-coding a port or binding to localhost is the #1 reason a health check fails and the deploy never goes live.',
      },
      {
        label: 'Push to GitHub, then create the Service',
        isText: true,
        text: [
          '1. Push your project to a GitHub repo',
          '2. Go to app.koyeb.com → sign up (GitHub works; no card for free)',
          '3. "Create Web Service" → "GitHub" → authorize + pick your repo',
          '4. Builder: Koyeb auto-detects your stack:',
          '   → "Buildpack" — it detects Node/Python/etc. from your files',
          '     (package.json, requirements.txt) and builds automatically',
          '   → "Dockerfile" — if a Dockerfile exists, choose this to use it',
          '5. Set the Run command if needed:',
          '   → Node:    npm start   (or node server.js)',
          '   → FastAPI: uvicorn main:app --host 0.0.0.0 --port $PORT',
          '   → Flask:   gunicorn --bind 0.0.0.0:$PORT app:app',
          '6. Instance type: choose "Free"',
          '7. Region: Singapore (closest to India) / Frankfurt / Washington DC',
          '8. Add environment variables (DATABASE_URL, secrets, etc.)',
          '9. Deploy — watch the build logs; you get a *.koyeb.app URL',
        ],
        note: 'The buildpack path means you often need NO Dockerfile at all for common stacks — Koyeb figures out how to build Node/Python apps. Add a Dockerfile only if you need full control or use a language buildpacks do not cover (e.g. Java).',
      },
      {
        label: 'Set the health check correctly',
        isText: true,
        text: [
          'Koyeb health-checks your service to decide if a deploy is healthy.',
          '',
          '→ By default it checks that your app is listening on the PORT',
          '→ If you have a health endpoint (e.g. GET /health returning 200),',
          '  set it under the service\'s Health checks settings',
          '→ A failing health check = the deploy is marked unhealthy and rolls',
          '  back — check that you bound to 0.0.0.0:$PORT first',
        ],
        note: 'If your first deploy "builds fine but never becomes healthy", it is almost always the port binding. Confirm the app listens on process.env.PORT / $PORT on host 0.0.0.0, and that any health-check path you configured actually returns 200.',
      },
    ],
  },

  {
    phase: '03',
    title: 'Deploy from a Docker image',
    color: '#2496ED',
    steps: [
      {
        label: 'Option A: let Koyeb build your Dockerfile from GitHub',
        isText: true,
        text: [
          'If your repo has a Dockerfile, the GitHub flow (Phase 02) can build it',
          'directly — just pick the "Dockerfile" builder. This is the simplest',
          'route for a Dockerized app: no registry needed.',
          '',
          'Choose this when your app is already containerized (e.g. a Spring Boot',
          'app, or anything with system dependencies buildpacks miss).',
        ],
        note: 'For most students with a Dockerfile in their repo, this is the easiest path — Koyeb clones, builds the image, and runs it, all from the source repo.',
      },
      {
        label: 'Option B: deploy a pre-built image from a registry',
        isText: true,
        text: [
          'If you already pushed an image to Docker Hub or GHCR:',
          '',
          '1. Build and push your image (see the Docker guide):',
          '   docker build -t yourname/myapp:latest .',
          '   docker push yourname/myapp:latest',
          '2. Koyeb → "Create Web Service" → "Docker" (deploy from image)',
          '3. Image: yourname/myapp:latest',
          '   (for a private image, add your registry credentials)',
          '4. Set the exposed port to match your app (e.g. 8000)',
          '5. Instance: Free · Region: Singapore · add env vars · Deploy',
        ],
        note: 'Deploying a pre-built image is useful when you build in CI or want the exact same image you ran locally. For a solo student project, building from GitHub (Option A) is usually less hassle than maintaining a registry.',
      },
      {
        label: 'Make sure the container exposes the right port',
        isText: true,
        text: [
          '→ Your Dockerfile should EXPOSE and your app should listen on the',
          '  port Koyeb expects (set it in the service, commonly matching $PORT)',
          '→ Bind to 0.0.0.0 inside the container, never 127.0.0.1',
          '→ Keep the image small (alpine/slim base, multi-stage build) so it',
          '  fits comfortably and deploys fast on the free instance',
        ],
        note: 'The same 0.0.0.0 + correct-port rule from the Docker guide applies here. Inside a container, 127.0.0.1 is unreachable from outside — bind to 0.0.0.0 or the health check will fail.',
      },
    ],
  },

  {
    phase: '04',
    title: 'Environment variables & connecting a database',
    color: '#F59E0B',
    steps: [
      {
        label: 'Set environment variables & secrets',
        isText: true,
        text: [
          'In the service settings → "Environment variables":',
          '→ Add plain vars (NODE_ENV=production) and Secrets (API keys, DB URLs)',
          '→ Koyeb "Secrets" are encrypted and reusable across services',
          '→ Reference them in your app via the normal env access',
          '  (process.env.X / os.environ["X"])',
          '',
          'Changing an env var triggers a redeploy so the new value takes effect.',
        ],
        note: 'Use Koyeb Secrets (not plain variables) for anything sensitive like DATABASE_URL or API keys. Never commit these to your repo.',
      },
      {
        label: 'Recommended: use an external database, not the free Koyeb DB',
        isText: true,
        text: [
          'The free Koyeb Postgres gives only 5 active-compute hours/month — fine',
          'for a quick test, but it will run out for anything used regularly.',
          '',
          'Better free databases to connect instead:',
          '→ Neon (Postgres) — 0.5 GB/project, data kept forever',
          '→ Turso (SQLite/libSQL) — 5 GB, no cold starts',
          '→ MongoDB Atlas — 512 MB, free forever',
          '→ Upstash Redis — for caching/sessions alongside the above',
          '',
          'Just set that provider\'s connection string as DATABASE_URL (a Secret)',
          'in your Koyeb service. Your app connects out to it normally.',
        ],
        note: 'Host the APP on Koyeb, but put the DATA in a dedicated free database service. This avoids the 5-hour Postgres limit entirely and keeps your data safe if you ever move the app to another host.',
      },
    ],
  },

  {
    phase: '05',
    title: 'Free-tier reality: Koyeb vs Render',
    color: '#EF4444',
    steps: [
      {
        label: 'Honest comparison & when to pick which',
        isText: true,
        text: [
          'Koyeb free web service:',
          '→ 512 MB RAM, 0.1 vCPU, 2 GB SSD; sleeps after ~1 hour idle',
          '→ Regions: Frankfurt, Washington D.C., Singapore',
          '→ Deploys from source (buildpacks) OR Docker OR a pushed image',
          '→ One free service per organization',
          '',
          'Render free web service (for comparison):',
          '→ 512 MB RAM; sleeps after ~15 minutes idle',
          '→ Deploys from source or Docker; huge, well-known docs',
          '→ Free Postgres exists but EXPIRES after 30 days',
          '',
          'Which should a student pick?',
          '→ Want a Singapore region (better latency from India) → Koyeb',
          '→ Want the most tutorials/community answers → Render',
          '→ Realistically: use BOTH as two separate free backend slots for',
          '  different projects, and keep data in Neon/Turso/Atlas either way',
          '',
          'Shared reality of ALL free backends:',
          '→ They sleep when idle → the first request after idle is slow (cold',
          '  start). Fine for demos/portfolios; not for latency-critical apps.',
          '→ You can ping the URL every few minutes (cron-job.org / GitHub',
          '  Actions) to reduce sleeping — but this uses shared free resources,',
          '  so use it sparingly and honestly.',
        ],
        note: 'The single biggest honest takeaway: Koyeb\'s free tier is now ONE small sleeping web service (the old $5.50 credit is gone). It is a great free backend slot — especially with the Singapore region — but treat cold starts and the tiny free Postgres as expected limitations, and lean on dedicated free databases for your data.',
      },
    ],
  },
]
