export const RENDER_POSTGRES_GUIDE = [
  {
    phase: '01',
    title: 'What is Render PostgreSQL and when to use it?',
    color: '#4ADE80',
    steps: [
      {
        label: 'Render PostgreSQL — easiest setup when using Render backend',
        isText: true,
        text: [
          'Render offers a free PostgreSQL database service.',
          '',
          'Key facts:',
          '✅ Free tier: 1GB storage',
          '✅ Easiest setup when your backend is also on Render',
          '✅ Internal URL: faster connections within Render network',
          '✅ Auto-linked to Render web services',
          '',
          '⚠️  Important limitation — 30-day expiry:',
          '   Render free PostgreSQL expires after 30 DAYS from creation',
          '   You get a 14-day grace period to upgrade before permanent deletion',
          '   After the grace period, the database and ALL data are permanently deleted',
          '   Render sends email warnings before expiry',
          '',
          'When to use Render PostgreSQL:',
          '→ Short-term demos and college project submissions',
          '→ When you want the simplest possible setup (auto-link feature)',
          '→ When data beyond 30 days does not matter',
          '',
          'When NOT to use Render PostgreSQL:',
          '→ Projects you want to keep alive long-term',
          '→ When you cannot afford to lose data',
          '',
          'Better alternatives for persistent data:',
          '→ Neon: 0.5GB/project, data preserved ← use this for long-term projects',
          '→ Supabase: 500MB free, never expires (may pause)',
        ],
        note: '⚠️  The 30-day expiry is the most important thing to know about Render PostgreSQL. Set a calendar reminder on day 20 to back up your data or migrate to Neon before the grace period ends.',
      },
    ],
  },

  {
    phase: '02',
    title: 'Create Render PostgreSQL database',
    color: '#4ADE80',
    steps: [
      {
        label: 'Step-by-step: create free Render PostgreSQL',
        isText: true,
        text: [
          '1. render.com → sign in with GitHub',
          '',
          '2. Click "New" → "PostgreSQL"',
          '   → Name: e.g. "myproject-db"',
          '   → Database: e.g. "mydb" (leave blank for auto-name)',
          '   → User: e.g. "mydbuser" (leave blank for auto-name)',
          '   → Region: same region as your web service',
          '   → PostgreSQL Version: 16 (latest)',
          '   → Plan: Free',
          '   → Click "Create Database"',
          '',
          '3. After creation, you see connection details:',
          '   → Internal Database URL — use this if app is ALSO on Render',
          '   → External Database URL — use this for local development',
          '   → Hostname, Port, Database, Username, Password shown separately',
          '',
          '4. Copy the relevant URL:',
          '   → For Render backend (same account):',
          '      Use Internal URL (stays within Render network, faster + free)',
          '   → For local development or Vercel/other hosts:',
          '      Use External URL',
        ],
        note: 'Always use the Internal Database URL when your web service and database are both on Render. It is faster (private network) and does not count against your bandwidth.',
      },
    ],
  },

  {
    phase: '03',
    title: 'Auto-link to Render Web Service',
    color: '#4ADE80',
    steps: [
      {
        label: 'The easiest connection — auto-link in Render dashboard',
        isText: true,
        text: [
          'Render has a feature that auto-fills DATABASE_URL for you:',
          '',
          '1. In your Render Web Service → click "Environment" tab',
          '2. Click "Add from Database"',
          '3. Select your PostgreSQL database from the dropdown',
          '4. Select "DATABASE_URL" from the connection types',
          '5. Render automatically sets DATABASE_URL to the Internal URL',
          '',
          'This is why Render PostgreSQL is the easiest option when',
          'your backend is also on Render — no copy-pasting credentials.',
          '',
          'After clicking Save:',
          '→ DATABASE_URL is set in your web service environment',
          '→ Render triggers a redeployment',
          '→ Your app connects to PostgreSQL automatically',
        ],
        note: 'The auto-link feature is unique to Render PostgreSQL. Neon and Supabase require manual copy-paste of connection strings. For quick setup on Render: use auto-link.',
      },
    ],
  },

  {
    phase: '04',
    title: 'Connect Render PostgreSQL to your backend',
    color: '#60A5FA',
    steps: [
      {
        label: 'Node.js — with Prisma',
        isText: true,
        text: [
          'DATABASE_URL is already set via auto-link (see Phase 03).',
          '',
          'prisma/schema.prisma:',
          '   datasource db {',
          '     provider = "postgresql"',
          '     url      = env("DATABASE_URL")',
          '   }',
          '',
          'Run: npx prisma db push',
          'Prisma creates tables in the Render database.',
        ],
        note: 'The DATABASE_URL from Render PostgreSQL Internal URL works directly with Prisma and pg without any modification.',
      },
      {
        label: 'Python/Django — with dj-database-url',
        isText: true,
        text: [
          'DATABASE_URL is set automatically by Render auto-link.',
          '',
          'In Django settings.py:',
          '   import dj_database_url',
          '   from decouple import config',
          '   DATABASES = {',
          '       "default": dj_database_url.config(',
          '           default=config("DATABASE_URL", default="sqlite:///db.sqlite3"),',
          '           conn_max_age=600,',
          '           ssl_require=True',
          '       )',
          '   }',
          '',
          'In Render Build Command:',
          '   pip install -r requirements.txt && python manage.py migrate',
          '',
          'Django migrations run automatically on every deploy.',
        ],
        note: 'ssl_require=True is important for Render PostgreSQL connections. Without SSL, the connection may be refused.',
      },
      {
        label: 'Spring Boot — JDBC URL conversion',
        isText: true,
        text: [
          'Render provides:',
          '   postgresql://user:pass@dpg-xxx.render.com:5432/mydb',
          '',
          'Spring Boot needs JDBC format:',
          '   jdbc:postgresql://dpg-xxx.render.com:5432/mydb',
          '',
          'In Render Environment Variables:',
          '   SPRING_DATASOURCE_URL = jdbc:postgresql://dpg-xxx.render.com:5432/mydb',
          '   SPRING_DATASOURCE_USERNAME = your_username',
          '   SPRING_DATASOURCE_PASSWORD = your_password',
          '',
          'Or use the auto-link + convert in application.properties:',
          '   spring.datasource.url=jdbc:postgresql://...',
        ],
        note: 'Render PostgreSQL does not need ?sslmode=require (unlike Neon) for internal connections. For external connections, you may want to add it.',
      },
    ],
  },

  {
    phase: '05',
    title: 'Back up data before 30-day expiry',
    color: '#EF4444',
    steps: [
      {
        label: 'Export your data before the database expires',
        isText: true,
        text: [
          'Render sends warning emails before the 30-day expiry.',
          'If you do not act, the database and ALL data are permanently deleted.',
          '',
          'Option 1: Export with pg_dump (command line):',
          '   pg_dump -h HOST -U USER -d DBNAME -f backup.sql',
          '   (Copy HOST, USER, DBNAME from Render PostgreSQL dashboard)',
          '',
          'Option 2: Export from Render dashboard:',
          '   Render → PostgreSQL → your database → Settings → Export data',
          '',
          'Option 3: Migrate to Neon (free, never expires):',
          '   1. Create a Neon project',
          '   2. Export from Render: pg_dump ... > backup.sql',
          '   3. Import to Neon: psql NEON_DATABASE_URL < backup.sql',
          '   4. Update DATABASE_URL in your Render web service to Neon URL',
          '   5. Redeploy',
          '',
          'Set a calendar reminder for around day 25 (a few days before the',
          '~30-day expiry) so you can migrate or back up in time.',
          '',
          'Best practice: for any project beyond a demo,',
          'start with Neon (free forever) instead of Render PostgreSQL.',
        ],
        note: 'The 30-day expiry applies only to the FREE tier Render PostgreSQL. Paid Render PostgreSQL plans do not expire.',
      },
    ],
  },
]


// ─── Streamlit → Streamlit Community Cloud ───────────────────────────────────
