/**
 * Builds public/sitemap.xml from live FE catalogs + static public hubs.
 * Run: node scripts/generate-sitemap.mjs  (also via npm run prebuild)
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const root = path.resolve(__dirname, '..')
const ORIGIN = 'https://learnforearn.in'
const today = new Date().toISOString().slice(0, 10)

const STATIC = [
  { loc: '/', priority: '1.0', changefreq: 'weekly' },
  { loc: '/ai-lab', priority: '0.95', changefreq: 'weekly' },
  { loc: '/deployment', priority: '0.95', changefreq: 'weekly' },
  { loc: '/aptitude', priority: '0.95', changefreq: 'weekly' },
  { loc: '/aptitude/quantitative', priority: '0.8', changefreq: 'monthly' },
  { loc: '/aptitude/logical', priority: '0.8', changefreq: 'monthly' },
  { loc: '/aptitude/verbal', priority: '0.8', changefreq: 'monthly' },
  { loc: '/aptitude/data-interpretation', priority: '0.8', changefreq: 'monthly' },
  { loc: '/fresher-instructions', priority: '0.9', changefreq: 'monthly' },
  { loc: '/fresher-instructions/career-guidance', priority: '0.85', changefreq: 'monthly' },
  { loc: '/missions', priority: '0.8', changefreq: 'weekly' },
  { loc: '/walk-ins', priority: '0.8', changefreq: 'weekly' },
  { loc: '/resume', priority: '0.85', changefreq: 'monthly' },
  { loc: '/about', priority: '0.7', changefreq: 'monthly' },
  { loc: '/contact', priority: '0.7', changefreq: 'monthly' },
  { loc: '/terms', priority: '0.3', changefreq: 'yearly' },
  { loc: '/privacy', priority: '0.3', changefreq: 'yearly' },
]

function extractAiLabPaths(src) {
  const paths = []
  const re = /\{\s*id:\s*'([^']+)'\s*,\s*category:\s*'([^']+)'/g
  let m
  while ((m = re.exec(src))) paths.push(`/ai-lab/${m[2]}/${m[1]}`)
  return [...new Set(paths)]
}

function extractDeployPaths(src) {
  const paths = []
  const re = /route:\s*'(\/deployment\/[^']+)'/g
  let m
  while ((m = re.exec(src))) paths.push(m[1])
  return [...new Set(paths)]
}

const aiSrc = fs.readFileSync(path.join(root, 'src/pages/ailab/aiLabData.js'), 'utf8')
const deploySrc = fs.readFileSync(path.join(root, 'src/pages/deployment/guideIndex.js'), 'utf8')

const aiPaths = extractAiLabPaths(aiSrc)
const deployPaths = extractDeployPaths(deploySrc)

const urls = [
  ...STATIC,
  ...aiPaths.map((loc) => ({ loc, priority: '0.75', changefreq: 'monthly' })),
  ...deployPaths.map((loc) => ({ loc, priority: '0.8', changefreq: 'monthly' })),
]

const body = urls.map(({ loc, priority, changefreq }) => `  <url>
    <loc>${ORIGIN}${loc === '/' ? '/' : loc}</loc>
    <lastmod>${today}</lastmod>
    <changefreq>${changefreq}</changefreq>
    <priority>${priority}</priority>
  </url>`).join('\n')

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Auto-generated by scripts/generate-sitemap.mjs — do not edit by hand. -->
<!-- Public crawlable hubs + AI Lab tools + deployment guides. Auth-only areas omitted. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${body}
</urlset>
`

const out = path.join(root, 'public/sitemap.xml')
fs.writeFileSync(out, xml, 'utf8')
console.log(`sitemap.xml written: ${urls.length} URLs (${aiPaths.length} AI Lab, ${deployPaths.length} deploy)`)
