/**
 * Builds public/sitemap.xml from the public, indexable routes only.
 * Run: node scripts/generate-sitemap.mjs  (wired into `npm run build` via prebuild)
 *
 * IMPORTANT: only list URLs that are BOTH crawlable (not Disallow'd in
 * robots.txt) AND indexable (not noindex in src/utils/documentTitle.js).
 * AI Lab tools, deployment guide details, Code Gym, Skill Arena, aptitude
 * topics, missions details, profiles and resumes are login-gated / noindex,
 * so they are deliberately omitted — listing them only produces
 * "Submitted URL blocked by robots.txt / marked noindex" errors in Search Console.
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { TIPS } from '../src/pages/tips/tipsContent.js'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const root = path.resolve(__dirname, '..')
const ORIGIN = 'https://learnforearn.in'
const today = new Date().toISOString().slice(0, 10)

const STATIC = [
  { loc: '/', priority: '1.0', changefreq: 'weekly' },
  { loc: '/aptitude', priority: '0.95', changefreq: 'weekly' },
  { loc: '/aptitude/quantitative', priority: '0.8', changefreq: 'monthly' },
  { loc: '/aptitude/logical', priority: '0.8', changefreq: 'monthly' },
  { loc: '/aptitude/verbal', priority: '0.8', changefreq: 'monthly' },
  { loc: '/aptitude/data-interpretation', priority: '0.8', changefreq: 'monthly' },
  { loc: '/missions', priority: '0.9', changefreq: 'weekly' },
  { loc: '/ai-lab', priority: '0.8', changefreq: 'weekly' },
  { loc: '/deployment', priority: '0.8', changefreq: 'weekly' },
  { loc: '/walk-ins', priority: '0.8', changefreq: 'weekly' },
  { loc: '/fresher-instructions', priority: '0.9', changefreq: 'monthly' },
  { loc: '/fresher-instructions/career-guidance', priority: '0.85', changefreq: 'monthly' },
  { loc: '/tips', priority: '0.85', changefreq: 'weekly' },
  { loc: '/resume', priority: '0.7', changefreq: 'monthly' },
  { loc: '/about', priority: '0.6', changefreq: 'monthly' },
  { loc: '/contact', priority: '0.5', changefreq: 'monthly' },
  { loc: '/terms', priority: '0.3', changefreq: 'yearly' },
  { loc: '/privacy', priority: '0.3', changefreq: 'yearly' },
]

const tipUrls = TIPS.map((t) => ({ loc: `/tips/${t.slug}`, priority: '0.8', changefreq: 'monthly' }))

const urls = [...STATIC, ...tipUrls]

const body = urls.map(({ loc, priority, changefreq }) => `  <url>
    <loc>${ORIGIN}${loc === '/' ? '/' : loc}</loc>
    <lastmod>${today}</lastmod>
    <changefreq>${changefreq}</changefreq>
    <priority>${priority}</priority>
  </url>`).join('\n')

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Auto-generated by scripts/generate-sitemap.mjs — do not edit by hand. -->
<!-- Public, indexable routes only. Auth-gated / noindex areas are omitted. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${body}
</urlset>
`

const out = path.join(root, 'public/sitemap.xml')
fs.writeFileSync(out, xml, 'utf8')
console.log(`sitemap.xml written: ${urls.length} URLs (${tipUrls.length} tips)`)
